name: 'CI'

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint_token:
    defaults:
        run:
          working-directory: ./token
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-lint-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-lint-${{ env.cache-name }}-
      - run: npm i
      - run: npm install -g solhint
      - run: solhint contracts/**/*.sol
  tests_token:
    defaults:
        run:
          working-directory: ./token
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-test-token-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-test-token-${{ env.cache-name }}-
      - run: npm i
      - name: Run Hardhat
        run: |
          npx hardhat node &
      - name: Compile contracts
        run: |
          npx hardhat compile --force
      - name: Run tests
        run: npm run test
      - name: Delete dbg files
        run: find ./artifacts/* -name "*.dbg.json" -type f -delete

  slither_token:
    name: Slither Token Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        continue-on-error: true
        id: slither
        with:
          node-version: 18
          sarif: results.sarif
          target: ./token
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}

  lint_migration:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./migration
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-lint-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-lint-${{ env.cache-name }}-
      - run: npm i
      - run: npm install -g solhint
      - run: solhint contracts/**/*.sol

  tests_migration:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./migration
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-test-token-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-test-token-${{ env.cache-name }}-
      - run: npm i
      - name: Run Hardhat
        run: |
          npx hardhat node &
      - name: Compile contracts
        run: |
          npx hardhat compile --force
      - name: Run tests
        run: npm run test 

  slither_migration:
            name: Slither Migration Analysis
            runs-on: ubuntu-latest
            permissions:
              contents: read
              security-events: write
            steps:
              - name: Checkout repository
                uses: actions/checkout@v2
              - name: Run Slither
                uses: crytic/slither-action@v0.4.0
                continue-on-error: true
                id: slither
                with:
                  node-version: 18
                  sarif: results.sarif
                  target: ./migration
              - name: Upload SARIF file
                uses: github/codeql-action/upload-sarif@v2
                with:
                  sarif_file: ${{ steps.slither.outputs.sarif }}
        